### PR TITLE
Build with config release on Windows

### PR DESCRIPTION
**Pull request by thomashampson**
There was an error in the bld.bat that meant it was being built with debug config rather than release.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thomashampson** [comment]
@conda-forge-admin, please add user @martyngigg

**Comment by thomashampson** [comment]
@conda-forge-admin, please add user @thomashampson

**Comment by thomashampson** [comment]
@conda-forge-admin, please add user @sf1919

**Comment by martyngigg** [comment]
@conda-forge-admin please rerender

**Comment by StephenSmith25** [comment]
Oops: Guess I was a bit confused about whether it was a multi-configuration generator. Thanks for fixing it!

**Pull request merged**
