### PR TITLE
v2.3.2 - Update and fix for windows build

### PR DESCRIPTION
**Pull request by ndevenish**
Fixing errors in bot PR.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Changes needed:
- External zlib and libzip are now _always_ used, I think because the vendored dependencies are now git submodules (and not available in the tarball?)
- Windows patches removed (the flag it was patching is no more) and added (some combinations of logic in the CMakeLists could lead to some `target_link_libraries` with transitive declarations and some without, that is invalid)
- General rerender

Closes #3.
Closes #4.
Closes #5.

### CODE REVIEW

**Comment by ndevenish** [comment]
Saw the `config.h` windows failures before the submodules were checked out. I'm assuming that between the previously successful version and this, lib3mf changed the way it included external dependencies slightly. Let's try using libzip and zlib from conda-forge (perhaps they didn't used to be available on windows?)

**Comment by ndevenish** [comment]
Okay, I think this is ready. Changes needed:
- External zlib and libzip are now _always_ used, I think because the vendored dependencies are now git submodules (and not available in the tarball?)
- Windows patches removed (the flag it was patching is no more) and added (some combinations of logic in the CMakeLists could lead to some `target_link_libraries` with transitive declarations and some without, that is invalid)
- General rerender

**Comment by StephenSmith25** [comment]
Brilliant work, thank you. Do you want to add yourself as a maintainer for this? No obligation to do so, I just do not use this package anymore so the help would be appreciated

**Comment by ndevenish** [comment]
Happy to, I’ll trigger the update separately

**Pull request merged**
